---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${NAME}-ingress
spec:
  rules:
  - host: api.ewetasker.cluster.gsi.dit.upm.es
    http:
      paths:
      - path: /
        backend:
          serviceName: ${NAME}
          servicePort: 5050
      - path: /wamp
        backend:
          serviceName: ${NAME}-crossbar-wamp
          servicePort: 8081
      - path: /http
        backend:
          serviceName: ${NAME}-crossbar-http
          servicePort: 8082
      - path: /mqtt
        backend:
          serviceName: ${NAME}-crossbar-mqtt
          servicePort: 1883
---
