---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${NAME}-crossbar-config
data:
    API: "$API_ENDPOINT"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ewetasker-crossbar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: ${NAME}-crossbar
        app: ${NAME}-crossbar
    spec:
      imagePullSecrets:
        - name: registry.cluster.gsi.dit.upm.es
      containers:
        - name : ${NAME}-crossbar
          image: ${IMAGEWTAGCROSSBAR}
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
          - name: wamp
            containerPort: 8081
          - name: http
            containerPort: 8082
          - name: mqtt
            containerPort: 1883
          envFrom:
            - configMapRef:
                name: ${NAME}-crossbar-config
---
